Update C_action_cards.php
bradleysigma/tirules pull request #1
Opened 2021-05-18 06:42 UTC by ctinfty

Mostly typos and two corrections which I've cleared through discord rules channels.

2021-05-18 07:13 UTC, ctinfty commented
Direct Hit cannot be used to destroy mechs, but x-89 omega could kill the last infantry on a planet barring the active player fom scoring Make an Example. A Planet currently cannot have multiple tech specialities.

2021-05-18 11:37 UTC, ctinfty commented on C_action_cards.php
> +    <li>If a player successfully resolves a <i>Construction Rider</i> while they own the <i>Minister of Industry</i> law, they use the <sc>Production</sc> ability of their units in the system where t
not sure on the wording here

2021-05-18 11:39 UTC, ctinfty commented on C_action_cards.php
> +    <li>A player cannot choose to destroy fewer than three infantry if there are any on the selected planet.</li>
again, not sure on the wording

2021-05-20 18:30 UTC, bradleysigma requested changes
Thank you for the changes so far. I've just got a few of comments, but other than that, looks good.

2021-05-20 18:30 UTC, bradleysigma commented on C_action_cards.php
> +    <li>A player may place fighters in systems that is at its capacity limit. If they do so, they must then remove a fighter or ground force from the space area of that system.</li>
(while you're here), `systems` should be `system` to match the rest of the line.

2021-05-20 18:30 UTC, bradleysigma commented on C_action_cards.php
> +    <li>A player cannot choose to destroy fewer than three infantry if there are any on the selected planet.</li>
I would add `(including zero)` to the first line, and make the second line to the effect of:
`<li>If the selected planet has three or fewer infantry on it, all infantry will be destroyed.</li>`

2021-05-20 18:30 UTC, bradleysigma commented on C_action_cards.php
> +    <li>If a player successfully resolves a <i>Construction Rider</i> while they own the <i>Minister of Industry</i> law, they use the <sc>Production</sc> ability of their units in the system where t
Seems fine.

2021-05-20 18:30 UTC, bradleysigma commented on C_agendas.php
> +    <li>Structures are unaffected by <i>Compensated Disarmament</i> except for the Titans of Ul&rsquo;s Hel&ndash;Titans .</li>
I would make the exception a subpoint.

2021-05-20 18:30 UTC, bradleysigma commented on C_agendas.php
> +    <li>If <i>Seed of an Empire</i> is resolved, and multiple players have the most or fewest victory points, they gain victory points in speaker order.</li>
(while your here) this can be shortened to just `If multiple players have...`.

2021-05-20 18:30 UTC, bradleysigma commented on C_agendas.php
> +    <li>The &ldquo;Against&rdquo; effect of Wormhole Reconstruction will cause each player to place command tokens into each system that contains an alpha, beta, delta or gamma wormhole and one or mo
`into` to `in`.

2021-05-20 18:30 UTC, bradleysigma commented on C_objectives.php
> +    <li>Trade goods may be spent as resources when scoring <i>Found a Golden Age</i>.</li>
Serves me right for copying and pasting. Though somehow the Erect a Monument entry is italicised.

2021-05-20 18:30 UTC, bradleysigma commented on C_objectives.php
> +    <li>The number of structures a planet has is irrelevant, if it has at least one.</li>
Re-add `on`, remove `has`.

2021-05-20 18:30 UTC, bradleysigma commented on C_objectives.php
> +    <li>The number of structures a planet has is irrelevant, if it has at least one.</li>
Re-add `on`, remove `has`.

2021-05-21 07:53 UTC, bradleysigma commented on C_action_cards.php
> +    <li>A player cannot choose to destroy fewer than three infantry if there are any on the selected planet.</li>
Hmmmm. Maybe just go the explicit route.
`<li>If the selected planet has three or fewer infantry on it, all infantry will be destroyed. Otherwise, three infantry will be destroyed.</li>`
But I'll probably approve whatever you decide to go with.

2021-05-21 08:36 UTC, bradleysigma approved these changes

2021-05-21 08:36 UTC, merged