Fixes to further component and faction notes
bradleysigma/tirules pull request #4
Opened 2021-05-21 20:50 UTC by ctinfty

2021-05-22 07:52 UTC, ctinfty commented on F_vuilraith.php
> -    <li>A unit is not adjacent to the system it is in; the <i>Vortex</i> ability cannot target a unit that is blockading one of the Vuil&rsquo;raith player&rsquo;s Dimensional Tears, unless there is
If a unit is blockading a space dock it cannot be captured anyway, so I don't think this is needed.

2021-05-22 14:48 UTC, bradleysigma commented on F_vuilraith.php
> -    <li>A unit is not adjacent to the system it is in; the <i>Vortex</i> ability cannot target a unit that is blockading one of the Vuil&rsquo;raith player&rsquo;s Dimensional Tears, unless there is
You're right. However, *Vortex* can also capture ground forces, so this note should be updated to something like:
`<li>A unit is not adjacent to the system it is in; the <i>Vortex</i> ability cannot target a ground force on another planet in the same systems as one of the Vuil&rsquo;raith player&rsquo;s Dimensional Tears, unless there is a second space dock in an adjacent system.</li>`

2021-05-22 15:17 UTC, ctinfty commented on F_vuilraith.php
> -    <li>A unit is not adjacent to the system it is in; the <i>Vortex</i> ability cannot target a unit that is blockading one of the Vuil&rsquo;raith player&rsquo;s Dimensional Tears, unless there is
I didn't think of that. It seems intuitively wrong, but RAW I agree with you. I'll make that change.

2021-05-22 15:45 UTC, bradleysigma requested changes
Again, a few changes.
Again, thanks for your help.

2021-05-22 15:45 UTC, bradleysigma commented on F_creuss.php
> +<h1>Creuss IFF <sub>(Promissory Note)</sub></h1>
Any citation on the capitalisation? The card is in all caps. Seems fine without a citation, but it would be nice to know for sure.

2021-05-22 15:45 UTC, bradleysigma commented on F_hacan.php
> +    <li>This ability may be triggered once for each dice roll, but may only be applied once per die. The Hacan player cannot spend two (or more) trade goods to apply +2 (or more) to a single die, but
My version had the redundant "only" and plural "dice". However, "dice roll" should be "die rolled". Probably best to just shorten the first sentence to:
> This ability may be triggered only once for each die rolled.

2021-05-22 15:45 UTC, bradleysigma commented on F_lizix.php
> +    <ol><li>If the L1Z1X player would have to place a structure, but there are none of that type left in their reinforcements, they may remove a structure of that type from any system that does not c
Move this to it's own point, not a sub-point.

2021-05-22 15:45 UTC, bradleysigma commented on F_mahact.php
> -    <li>The system the combat is taking place in is considered the active system during that that combat.</li>
I believe this is the community consensus until v2.1 is released, otherwise a whole bunch of abilities (such as Yin's Devotion) stop working.

2021-05-22 15:45 UTC, bradleysigma commented on F_muaat.php
> +    <li>If the Muaat player owns <i>Magmus Reator &Omega;</i>, and resolves this ability during a tactical action, they will be able to produce units during the <b>Production</b> step, if there are s
> ... if the Muaat player still has units in the system during the production step.

2021-05-22 15:45 UTC, bradleysigma commented on F_lizix.php
> +    <li>This ability is mandatory.</li>
> The L1Z1X player must mandatory place a PDS and a Space Dock.

(to be consistent with elsewhere).

2021-05-22 15:45 UTC, bradleysigma commented on F_nomad.php
> +    <li>The flagship still has a cost of 8, so it cannot be produced with abilities that are limited by the cost of units, such as the <i>Integrated Economy</i> technology or Muaat&rsquo;s <i>Umbat</
The _Scuttle_ action card might be worth mentioning, either in place of or after the Muaat agent.
If you leave the Muaat agent, it should read as
> ... or the Muaat player's agent.

Only the Nomad gets their agents named, and adding in "player's" avoids the need to possessivise "Creuss" etc.

2021-05-22 15:45 UTC, bradleysigma commented on F_norr.php
> +    <li>The <i>Parley</i> action card will place the committed ground forces in the space area of the active system. As the N&rsquo;orr player will not have enough capacity in the space area for thei
Maybe?
> ... all ground forces from that planet now in the space area of that system.

2021-05-22 15:45 UTC, bradleysigma commented on F_saar.php
> +    <li>If an asteroid field contains only Floating Factories and transported ground forces, it can still be activated by other players.</li>
Mirrage makes the "transported" mildly inaccurate.

2021-05-22 15:45 UTC, bradleysigma commented on F_sol.php
> +    <li>If the Sol player chooses one of the L1Z1X player&rsquo;s Annihilator mechs on a different planet or in the space area, then this ability applies to dice rolls for that unit&rsquo;s bombardme
While you're here:
> L1Z1X player uses their <sc>Harrow</sc> ability.

2021-05-22 15:45 UTC, bradleysigma commented on F_ul.php
> +    <li>Only sleeper tokens present in the system when it is activated may be replaced with PDS.</li>
"sleeper tokens" should match with "PDSs" wrt plurals (for multi-planet systems).
(The rulebook uses "PDS units", but that the coward's method.)

2021-05-22 15:45 UTC, bradleysigma commented on F_vuilraith.php
> +    <ol><li>For example, consider a series of systems A&ndash;B&ndash;C&ndash;. Only systems connected by a &ldquo;&ndash;&rdquo; are adjacent. Systems &ldquo;A&rdquo;, &ldquo;B&rdquo; and &ldquo;C&r
That `M` should be there, but it should also be a capital (it's referenced in the example).

2021-05-22 15:45 UTC, bradleysigma commented on F_vuilraith.php
> +    <ol><li>Most notably, a flagship can never be captured by <i>Vortex</i>.</li></ol>
Seems unnecessary. ¯\\\_(ツ)\_/¯

2021-05-22 15:45 UTC, bradleysigma commented on F_winnu.php
> +    <li>If the Winnu player chooses the <i>Trade</i> strategy card for this ability and the Winnu player chooses a player to resolve the secondary without spending a command token via the primary abi
> the

2021-05-22 19:41 UTC, ctinfty commented on F_creuss.php
> +<h1>Creuss IFF <sub>(Promissory Note)</sub></h1>
I only have RoboDane as citation 😄 
![image](https://user-images.githubusercontent.com/58255027/119239013-6619be00-bb46-11eb-8153-58497303747b.png)
But it also seems like a abbreviation to me.

2021-05-22 20:29 UTC, ctinfty commented on F_lizix.php
> +    <li>This ability is mandatory.</li>
Might not be a PDS and a Space Dock. My suggestion for this and the following point:
```
<li>If the L1Z1X player would have to place a structure, but there are none of that type left in their reinforcements, they may remove a structure of that type from any system that does not contain one of their command tokens and place that instead.</li>
<li>The L1Z1X player must mandatorily replace every structure. However, if there are none of that type in their reinforcements they are not forced to do so.</li>
```

2021-05-22 20:29 UTC, ctinfty commented on F_saar.php
> +    <li>If an asteroid field contains only Floating Factories and transported ground forces, it can still be activated by other players.</li>
Should I then also add PDS?

2021-05-22 20:29 UTC, ctinfty commented on F_ul.php
> +    <li>Only sleeper tokens present in the system when it is activated may be replaced with PDS.</li>
I cannot find "PDSs" anywhere else in the files. For example in line 42 of this file:
`<li>Only PDS present in the system when it is activated may be replaced with the <i>Ouranos</i>.</li>`

2021-05-22 20:29 UTC, ctinfty commented on F_vuilraith.php
> +    <ol><li>Most notably, a flagship can never be captured by <i>Vortex</i>.</li></ol>
What of this necessary? 😄
I found it noteworthy, but I'll remove it if you don't want it.

2021-06-28 05:01 UTC, bradleysigma commented on F_mahact.php
> -    <li>The system the combat is taking place in is considered the active system during that that combat.</li>
The recent Dane FAQ confirms this.
https://docs.google.com/document/d/1_93kw7KkzvAXoQAxRioxo7iAt-Ar6BMIxdNf4Lv25rI/edit
This document does contain a bunch of rulings, which I'll add to the site at some point.

2021-06-28 05:06 UTC, bradleysigma commented on F_saar.php
> +    <li>If an asteroid field contains only Floating Factories and transported ground forces, it can still be activated by other players.</li>
Maybe
> If an asteroid field contains non-ship units belonging to the Saar player, it can still be activated by other players.

2021-06-28 05:07 UTC, bradleysigma commented on F_ul.php
> +    <li>Only sleeper tokens present in the system when it is activated may be replaced with PDS.</li>
Hmmmm. I may be thinking of something I had in the early stages. This is fine.

2021-06-28 05:09 UTC, bradleysigma commented on F_vuilraith.php
> +    <ol><li>Most notably, a flagship can never be captured by <i>Vortex</i>.</li></ol>
If you do keep this, could you change the "most notably" to "as such" or "consequently" or similar.

2021-06-29 18:36 UTC, ctinfty commented on F_vuilraith.php
> +    <ol><li>Most notably, a flagship can never be captured by <i>Vortex</i>.</li></ol>
I dropped it

2021-07-01 00:26 UTC, merged