Updates from the Dane FAQ
bradleysigma/tirules pull request #5
Opened 2021-07-01 15:14 UTC by bradleysigma

https://docs.google.com/document/d/1_93kw7KkzvAXoQAxRioxo7iAt-Ar6BMIxdNf4Lv25rI

2021-07-02 20:02 UTC, ctinfty requested changes
Thanks for the promotion 😀 
Please take my suggestions about language with a grain of salt. I'm not a native speaker.

2021-07-02 20:02 UTC, ctinfty commented on R_wormholes.php
> +        <li>A player may move a ship back and forward through a wormhole between two systems any number of times, if its movement value is high enough.</li>
```suggestion
        <li>A player may move a ship back and forth through a wormhole between two systems any number of times, if its movement value is high enough.</li>
```

2021-07-03 00:01 UTC, bradleysigma commented on C_action_cards.php
> +    <li>If <i>Reflective Shielding</i> is played after a ship uses its <sc>Sustain Damage</sc> ability during any other time (for example, when the Creuss player uses their <i>Dimensional Splicer</i>
Done.

2021-07-03 00:02 UTC, bradleysigma commented on C_technology.php
> +    <li>The ground forces may be removed from on a planet or from in a space area.</li>
Both should work, but the extra words add some emphasis.

2021-07-03 00:02 UTC, bradleysigma commented on F_creuss.php
> +	    <li>The Creuss player cannot remove a ground force to create capacity for a fighter.</li>
Done.

2021-07-03 00:03 UTC, bradleysigma commented on F_mahact.php
> +    <!--li>The Mahact player may only move the Empyrean player&rsquo;s ships into a nebula.</li-->
Until the change is released in a LRR, I'll leave it like this for now.

2021-07-03 00:03 UTC, bradleysigma commented on F_mahact.php
> +    <li>The Mahact player may end their own turn and gain their own spent command token from their fleet pool.</li>
Changed to
`<li>The Mahact player may use the ability to end their own turn and gain their own spent command token from their fleet pool.</li>`

2021-07-03 00:04 UTC, bradleysigma commented on F_muaat.php
> +    <li>Any command tokens and the Muaat player&rsquo;s units on the replaced system tile are transferred to the new supernova tile. Any Creuss wormhole tokens are returned to the Creuss player. All
Done.

2021-07-03 00:04 UTC, bradleysigma commented on F_norr.php
> +        <li>If another player plays the N&rsquo;orr player&rsquo;s <i>Ceasefire</i> promissory note, they cannot commit any ground forces to planets in the active system during this action.</li>
They can. Added this in.

2021-07-03 00:04 UTC, bradleysigma commented on F_ul.php
> +    <li>The Ul player cannot place a PDS on a planet that already has two of their PDS on it. As such, they are unable to place a Hecatoncheries on a planet with two of their PDS using its <sc>Deploy
Done everywhere.

2021-07-03 00:05 UTC, bradleysigma commented on F_ul.php
> +    <li>The Ul player cannot place a PDS on a planet that already has two of their PDS on it. As such, they are unable to place a Hecatoncheries on a planet with two of their PDS using its <sc>Deploy
Done.

2021-07-03 00:06 UTC, bradleysigma commented on R_nebula.php
> +    <li>A future rule change will allow ships to move into nebulae when it is not the active system.</li>
Did the former.

2021-07-03 08:49 UTC, ctinfty commented on F_norr.php
> +    <li>The <i>Dominus Orb</i> relic does not allow the N&rsquo;orr player to committ ground forces from systems containing their command tokens.</li>
```suggestion
    <li>The <i>Dominus Orb</i> relic does not allow the N&rsquo;orr player to commit ground forces from systems containing their command tokens.</li>
```
my bad

2021-07-03 08:49 UTC, ctinfty commented on F_ul.php
>      <li>When the Ul player would place multiple PDS during a single step, they may resolve a <sc>Deploy</sc> ability to place one Hecatoncheries for any or all of those PDS.</li>
```suggestion
    <li>When the Ul player would place multiple PDS during a single step, they may resolve a <sc>Deploy</sc> ability to place one Hecatoncheires for any or all of those PDS.</li>
```

2021-07-03 08:49 UTC, ctinfty commented on F_ul.php
>      <li>A <sc>Deploy</sc> ability may only be resolved for units in a player&rsquo;s reinforcements. If all four of the Hecatoncheries are already on the board, no Hecatoncheries may be deployed.</li
```suggestion
    <li>A <sc>Deploy</sc> ability may only be resolved for units in a player&rsquo;s reinforcements. If all four of the Hecatoncheires are already on the board, no Hecatoncheires may be deployed.</li>
```

2021-07-03 08:52 UTC, ctinfty commented
Other than these it looks great!

2021-07-03 11:23 UTC, ctinfty commented
I took the liberty to fix those last few myself. Feel free to merge if you're satisfied.

2021-07-03 12:59 UTC, bradleysigma commented on F_ul.php
>      <li>When the Ul player would place multiple PDS during a single step, they may resolve a <sc>Deploy</sc> ability to place one Hecatoncheries for any or all of those PDS.</li>
I could have sworn I did replace all...

2021-07-03 13:02 UTC, merged